language: node_js

script:
  - "npm run travis"

node_js:
  - "16"
  - "18"
  - "19"
  - "20"

branches:
  except:
    - /^v\d+\./

matrix:
  fast_finish: true
  include:
    - node_js: "18"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
